### ISSUE TITLE
Marking_store method not implemented

### ISSUE THREAD

**Issue by AurelienMendes** [zerodahero/laravel-workflow#12]
Hi,

From the Symfony documentation (https://symfony.com/doc/4.4/workflow.html#creating-a-workflow) 
 and from the Symfony blog (https://symfony.com/blog/new-in-symfony-4-3-workflow-improvements#simpler-configuration) you can see that they modify a little the `marking_store` property in the config file.
```
framework:
    workflows:
        article:
            type: workflow
            marking_store:
                type: method # This will be the default value in Symfony 5.0
                property: marking # This is the default value, it could be omitted
        task:
            type: state_machine
            marking_store:
                type: method # This will be the default value in Symfony 5.0
                property: state

```
And they add a new `MethodMarkingStore` class that implements the `MarkingStoreInterface`.

Unfortunately in your `WorkflowRegistry` you set the marking_store with the `getMarkingStoreInstance()` method which doesn't take into account those Symfony modifications.
```php
protected function getMarkingStoreInstance(array $workflowData)
    {
        $markingStoreData = isset($workflowData['marking_store']) ? $workflowData['marking_store'] : [];
        $arguments = isset($markingStoreData['arguments']) ? $markingStoreData['arguments'] : [];

        if (isset($markingStoreData['class'])) {
            $className = $markingStoreData['class'];
        } elseif (isset($markingStoreData['type']) && $markingStoreData['type'] === 'multiple_state') {
            $className = MultipleStateMarkingStore::class;
        } else {
            $className = SingleStateMarkingStore::class;
        }

        $class = new \ReflectionClass($className);

        return $class->newInstanceArgs($arguments);
    }
```
which means we can't use the new marking_store formalism.

Do you think you can have a look on this ?

Thank !
